---
title: "NMFComparison"
output: html_document
editor_options: 
  chunk_output_type: console
---

Read in results generated by scikit-learn NMF function
```{r}
#cell matrix
cellMatrix = data.table::fread("data/NB_NMD_Cell_Matrix.tsv")

#tidy
cellMatrix = cellMatrix[-1,-1]
colnames(cellMatrix) = paste("Pattern", c(1:7))
cellMatrix = as.matrix(cellMatrix)

#add cell labels 
inputMatrix = readRDS("data/SchepCountMatrix99Filtered.rds")
rownames(cellMatrix) = colnames(inputMatrix)


#peak matrix
peakMatrix = as.matrix(data.table::fread("data/NB_NMD_Peak_Matrix.tsv"))

#tidy
peakMatrix = peakMatrix[-1,-1]
colnames(peakMatrix) = paste("Pattern", c(1:7))

#add peak labels
rownames(peakMatrix) = rownames(inputMatrix)
```


Plot the cell matrix weights against known cell line of origin
```{r}
cellTypes <- colnames(inputMatrix)
cellTypes <- plyr::mapvalues(as.factor(cellTypes), from = c("BJ","GM","GM12878","GM12878rep2","H1ESC","HL60","K562","LMPP","PB1022"   ,"SU070","SU353","TF1"), to = c("Fibroblasts", "GMLCL 1","GMLCL 2 Rep1","GMLCL 2 Rep2","H1ESCs","HL60 Leukemia","K562 Erythroleukemia","LMPP","Monocyte","AML Patient 070","AML Patient 353","TF1 Erythroblast"))

#vector of colors to plot cell types by
col <- c("salmon", 'aquamarine', 'aquamarine3', "aquamarine4", "darkorchid1", 'limegreen', "magenta", "orangered", "darkgreen", "darkred", "red3", "darkorange")

ATACCoGAPS::cgapsPlot(cellMatrix, cellTypes, matrix = TRUE, col)



#colors to plot patterns by
rowColors <- c(RColorBrewer::brewer.pal(7, "Dark2"))

#plot heatmap
ATACCoGAPS::heatmapPatternMatrix(cellMatrix, cellTypes, cellCols = col, rowColors = rowColors, col = viridis::magma(n=19), matrix = TRUE)

```


Find peaks associated with each pattern
```{r}
peakList = vector("list", 7)
for(i in 1:7) {
  peakMSub = peakMatrix[,i]
  top50peaks = names(sort(peakMSub, decreasing = T)[1:50])
  peakList[[i]] = top50peaks
}

#subset ATAC counts to just these peaks in order


for(i in seq_along(peakList)){
  
  tmp = inputMatrix[which(rownames(inputMatrix) %in% peakList[[i]]),]
  if(i == 1) {
    subsetATAC = tmp
  }
  else {
    subsetATAC = rbind(subsetATAC, tmp)
  }
}

#binarize for plotting
binarizedSubset = (subsetATAC > 0) + 0

#order by cell type
binarizedSubset = rbind(binarizedSubset, cellTypes)
binarizedSubset = binarizedSubset[,order(binarizedSubset[351,])]
binarizedSubset = binarizedSubset[-c(351),]

colColors = col[as.numeric(sort(cellTypes))]


rowCols = character(350)
  j=1
  for(i in 1:7){
    color = rep(rowColors[i], 50)
    rowCols[j:(j+50-1)] = color
    j=j+50
  }

gplots::heatmap.2(binarizedSubset, density.info="none", trace="none",
                      dendrogram='none', Rowv=FALSE, Colv=FALSE,
                      ColSideColors = colColors, RowSideColors = rowCols,
                      labRow = NA, labCol = as.character(sort(cellTypes)), col = viridis::plasma(n = 2))
```


Try first finding which pattern a peak most strongly associates with and then repeat from there
```{r}
peakPatterns = apply(peakMatrix, 1, function(x) {which(x == max(x))})

peakMatrixList = vector("list", 7)
for(i in 1:7){
  peakMatrixList[[i]] = peakMatrix[which(peakPatterns == i), i]
}

peakList = vector("list", 7)
for(i in 1:7) {
  peakMSub = peakMatrixList[[i]]
  top50peaks = names(sort(peakMSub, decreasing = T)[1:50])
  peakList[[i]] = top50peaks
}

#subset ATAC counts to just these peaks in order
for(i in seq_along(peakList)){
  
  tmp = inputMatrix[which(rownames(inputMatrix) %in% peakList[[i]]),]
  if(i == 1) {
    subsetATAC = tmp
  }
  else {
    subsetATAC = rbind(subsetATAC, tmp)
  }
}

#binarize for plotting
binarizedSubset = (subsetATAC > 0) + 0

#order by cell type
binarizedSubset = rbind(binarizedSubset, cellTypes)
binarizedSubset = binarizedSubset[,order(binarizedSubset[351,])]
binarizedSubset = binarizedSubset[-c(351),]

colColors = col[as.numeric(sort(cellTypes))]


rowCols = character(350)
  j=1
  for(i in 1:7){
    color = rep(rowColors[i], 50)
    rowCols[j:(j+50-1)] = color
    j=j+50
  }

gplots::heatmap.2(binarizedSubset, density.info="none", trace="none",
                      dendrogram='none', Rowv=FALSE, Colv=FALSE,
                      ColSideColors = colColors, RowSideColors = rowCols,
                      labRow = NA, labCol = as.character(sort(cellTypes)), col = viridis::plasma(n = 2))
```
Improves differentiation considerably, but still well short of CoGAPS


